frame = 'none'

[font]
size = 14
hinting = "slight"
edging = "subpixelantialias"

[[font.normal]]
family = "MonoLisa Variable"
style = "Medium"

[[font.normal]]
family = "Symbols Nerd Font"

[[font.bold]]
family = "MonoLisa Variable"
style = "Bold"

[[font.italic]]
family = "MonoLisa Variable"
style = "Medium Italic"

[[font.bold_italic]]
family = "MonoLisa Variable"
style = "Bold Italic"
