[default_apps]
terminal = "kitty"
browser = "/opt/zen-browser-bin/zen %u"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "eur"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock/icons"]
icon_size = 22
use_base_css = true
use_system_theme = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]
num_shortcuts = 5

[behavior]
use_xdg_data_dir_icons = true
animate = true
use_lr_nav = false

[keybinds]
"control-k" = "up"
"control-j" = "down"
"control-h" = "left"
"control-l" = "right"
"control-i" = "context"
"control" = "modifier"
"return" = "exec"
"control-return" = "exec_inplace"

[files]
config = "~/.config/sherlock/config.toml"
css = "~/.config/sherlock/main.css"
fallback = "~/.config/sherlock/fallback.json"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "~/.cache/sherlock/desktop_files.bin"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = true

[search_bar_icon]
enable = true
icon = "system-search-symbolic"
icon_back = "sherlock-back"
size = 22
