[general]
font-sans = "Noto Sans"
font-mono = "MonoLisa Variable"

[bar]
scale = 0.699999988079071
bg = "bg-base"
background-opacity = 67
button-variant = "icon-square"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "clock",
    "world-clock",
    "weather",
    "media",
    { name = "System", modules = [
    "cpu",
    "ram",
    "netstat",
] },
]
center = ["ext-workspaces"]
right = [
    "systray",
    "bluetooth",
    "network",
    "brightness",
    "volume",
    "dashboard",
]

[styling.palette]
bg = "#000000"
surface = "#000000"
elevated = "#111827"
fg = "#9ca3af"
fg-muted = "#9ca3af"
primary = "#8b68cf"
red = "#f472b6"
yellow = "#facc15"
green = "#2dd4a8"
blue = "#7ecae5"

[modules.bluetooth]
label-show = false

[modules.cava]
stereo = true
style = "wave"

[modules.clock]
format = "%a %d %b %H:%M"

[modules.dashboard]
icon-bg-color = "transparent"

[modules.network]
label-show = false

[modules.power]
right-click = "systemctl poweroff"
middle-click = "systemctl reboot"

[modules.weather]
location = "Tallinn"
units = "metric"
format = "{{ temp }}{{ temp_unit }} {{ condition }}"
time-format = "24h"

[modules.world-clock]
format = "{{ tz('America/New_York', '%H:%M %Z') }}"
border-color = "auto"
icon-bg-color = "auto"
label-color = "auto"

[wallpaper]
cycling-same-image = true

[[wallpaper.monitors]]
name = "*"
fit-mode = "fill"
wallpaper = "/home/azdanov/Pictures/Wallpapers/limine-splash.png"
