# https://aider.chat/docs/config/aider_conf.html
auto-commits: false
attribute-author: false
attribute-committer: false

# https://aider.chat/docs/leaderboards/
model: openrouter/anthropic/claude-3.7-sonnet
# You need to have the API keys defined somewhere when you run `aider`
#     https://aider.chat/docs/config/api-keys.html
# OPENROUTER_API_KEY=???
