set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g status-style "fg=#cad3f5,bg=#24273a,none"
set -g window-status-separator ""
set -g window-status-activity-style "fg=#cad3f5,bg=#24273a,none"

set -g pane-border-style 'fg=#363a4f'
set -g pane-active-border-style 'fg=#f5a97f'

set-window-option -g xterm-keys on

set -s escape-time 0

set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-option -g detach-on-destroy off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

run '~/.tmux/plugins/tpm/tpm'
