" Source a main configuration file if available.
if filereadable("/etc/vim/vimrc")
  source /etc/vim/vimrc
endif

" Vim and Neovim share the same configuration file.
let data_dir = expand('$HOME/.vim')

" Set Leader to Space (with \ and , as aliases)
let mapleader = " "
nmap <bslash> <space>
nmap , <space>

syntax on " Enable syntax highlighting
filetype on " Enable Vim to detect the type of file being edited
filetype indent on " Load an indent file for the detected file type
filetype plugin on " Enable plugins and load the plugin for the detected file type
filetype plugin indent on  " Load plugins according to detected filetype.

" Enable 24-bit color support
if has('termguicolors')
  set termguicolors
endif

" Turn on mouse support in all modes.
set mouse=a
" Enter insert mode on left-click.
nnoremap <LeftMouse> <LeftMouse>i

" Show line numbers
set number
" Show relative line numbers
set relativenumber

" Automatically indent new lines to match the indentation of the previous line
set autoindent
" Use spaces instead of tabs for indentation
set expandtab
" Be smart about inserting tabs.
set smarttab
" When pressing the Tab key, insert 4 spaces
set softtabstop=4
" Set the width for autoindents (like using the >> command) to 4 spaces
set shiftwidth=4
" Round indent to the nearest multiple of 'shiftwidth'
set shiftround

" Use smart case during searches.
set ignorecase
set smartcase

" More natural splitting
set splitbelow  " Open new windows below current one.
set splitright  " Open new windows right of current one.

" Enable faster screen redraw
set ttyfast
" Redraw the screen only when necessary to reduce flickering
set lazyredraw

" Show non-printable characters.
" set list
if has('multi_byte') && &encoding ==# 'utf-8'
  let &listchars = 'tab:├─┤,space:·,extends:❯,precedes:❮,nbsp:±'
else
  let &listchars = 'tab:|-|,space:.,extends:>,precedes:<,nbsp:.'
endif

" Remove trailing whitespace on save.
autocmd BufWritePre * :%s/\s\+$//e

" Configure what file types to ignore.
let g:lastplace_ignore = "gitcommit,gitrebase,svn,hgcommit"
" Configure buffer types to ignore.
let g:lastplace_ignore_buftype = "quickfix,nofile,help"
" Automatically open folds when jumping to the last edit position.
let g:lastplace_open_folds = 0

" Syntax highlighting for Markdown fenced code blocks
let g:markdown_fenced_languages = [
  \ 'bash',
  \ 'console=sh',
  \ 'sh',
  \ 'shell=sh',
  \ 'zsh',
  \ 'html',
  \ 'javascript',
  \ 'typescript',
  \ 'css',
  \ 'json',
  \ 'c',
  \ 'go',
  \ 'rust',
  \ 'julia',
  \ 'python',
  \ 'vim',
  \ 'vimscript=vim',
\ ]

" Keep a backup across sessions by storing it in a file.
set backup
let &backupdir = data_dir . '/backup//'
" Create directory if missing
if !isdirectory(&backupdir)
  execute '!mkdir -p ' . &backupdir
endif

" Never skip backups.
set backupskip=

" Keep swap files around.
let &directory = data_dir . '/swap//'
" Create directory if missing
if !isdirectory(&directory)
  execute '!mkdir -p ' . &directory
endif

" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
  set undofile
  let &undodir = data_dir . '/undo//'
  " Create directory if missing
  if !isdirectory(&undodir)
    execute '!mkdir -p ' . &undodir
  endif
endif

" Tell vim to remember certain things when we exit
"  '100  :  marks will be remembered for up to 100 previously edited files
"  "20000:  will save up to 20,000 lines for each register
"  :200  :  up to 200 lines of command-line history will be remembered
"  s20   :  up to 20 kilobytes will be saved for each register
"  %     :  saves and restores the buffer list
"  h     :  disables search highlighting when Vim starts
"  n...  :  where to save the viminfo files
set viminfo='100,\"20000,:200,s20,%,h,n~/.viminfo

" As-you-type autocomplete.
set completeopt=preview,menu,menuone,noselect,noinsert

if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" The list of vim-plug plugins.
call plug#begin(data_dir . '/plugged')
  " Basic plugins
  Plug 'tpope/vim-sensible'    " Sensible defaults
  " Basic enhancements
  Plug 'tpope/vim-sleuth'      " Automatic indentation detection
  Plug 'tpope/vim-surround'    " Surroundings
  " Language support
  Plug 'tpope/vim-markdown'
  " Status line
  Plug 'itchyny/lightline.vim' " Status line
  " Fuzzy finder
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  " Coding enhancements
  Plug 'github/copilot.vim'  " GitHub copilot
  " Colors
  Plug 'catppuccin/vim', { 'as': 'catppuccin' } " Theme
call plug#end()

" Disable the default status line.
set noshowmode
" Set the theme
autocmd VimEnter * colorscheme catppuccin_macchiato
let g:lightline = {'colorscheme': 'catppuccin_macchiato'}
