---@see https://github.com/nvim-treesitter/nvim-treesitter
---@see https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/plugins/treesitter.lua
---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "c",
      "cmake",
      "css",
      "dockerfile",
      "fish",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "html",
      "http",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "kotlin",
      "lua",
      "markdown",
      "markdown_inline",
      "nginx",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
    },
  },
}
