return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "dockerfile",
      "fish",
      "git_config",
      "gitattributes",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "regex",
      "scss",
      "sql",
      "toml",
      "tsx",
      "typescript",
      "vue",
      "xml",
      "yaml",
    },
  },
}
