[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[window]
dimensions = { columns = 115, lines = 33 }
# position = { x = 180, y = 234 }
# padding = { x = 2, y = 2 }
# option_as_alt = "OnlyLeft"
decorations = "None"
startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 5000

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 14.0

# [terminal]
# shell.program = "tmux"
# shell.args = ["new-session", "-A", "-D", "-s", "Home"]
