[bar.default]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "recorder",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
widget_spacing = 12

[brightness]
enable_ddcutil = true

[config]

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "dark_mode"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
magnification_scale = 1.0500000007450581
pinned = [ "helium", "nemo", "kitty" ]
reserve_space = false
show_dots = true

[location]
address = "Tallinn"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1720.0
    cy = 1321.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[plugin_settings."noctalia/screen_recorder"]
video_codec = "av1"

[plugins]
enabled = [ "noctalia/screen_recorder" ]

[shell]
clipboard_image_action_command = "satty -f -"
polkit_agent = true
telemetry_enabled = true

    [shell.panel]
    launcher_session_search = true

    [shell.screenshot]
    directory = "/home/azdanov/Pictures/Screenshots"

[templates.niri]
input_path = "~/.config/noctalia/templates/niri.kdl"
output_path = "~/.config/niri/noctalia.kdl"

[theme]
community_palette = "Kanagawa Paper"
mode = "dark"
source = "community"

    [theme.templates]
    builtin_ids = [ "niri" ]

[wallpaper]
directory = "/home/azdanov/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/azdanov/Pictures/Wallpapers/limine-splash.png"

    [wallpaper.last]
    path = "/home/azdanov/Pictures/Wallpapers/limine-splash.png"

[widget.clock]
format = "{:%H:%M %a, %b %d}"
tooltip_format = "{:%T %F}"

[widget.media]
hide_when_no_media = true

[widget.recorder]
type = "noctalia/screen_recorder:recorder"
